server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否将自己注册为服务
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:9000/eureka/
spring:
  application:
    name: eureka-server-2