server:
  port: 9000
eureka:
  instance:
    hostname: eureka-server-3
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔(默认是30秒)
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔(默认是90秒)
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位(默认是60秒)
    enable-self-preservation: true #设置为false表示关闭保护模式
  client:
    #false表示不向注册中心注册自己。
    registerWithEureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: true
#    register-with-eureka: false #是否将自己注册为服务
    service-url:
      defaultZone: http://eureka-server-1:8888/eureka/,http://eureka-server-2:8889/eureka/
spring:
  application:
    name: eureka-server-2