spring:
  application:
    name: eureka-client
server:
  port: 8889

eureka:
  client:
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:9000/eureka/