server:
  port: 8889
eureka:
  instance:
    hostname: eureka-server-2
  client:
    #false表示不向注册中心注册自己。
    registerWithEureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: false
#    register-with-eureka: false #是否将自己注册为服务
    service-url:
      defaultZone: http://eureka-server-1:8888/eureka/,http://eureka-server-3:9000/eureka/
spring:
  application:
    name: eureka-server-3