server:
  port: 9003
spring:
  cloud:
    gateway:
      #可以根据请求参数,cookie,host,请求时间,请求头等进行校验判断路由, 下面根据先后顺序转发
      routes:
        - id: eureka-server-2
          uri: http://httpbin.org/get
          predicates:
            - Path=/test/**
        - id: eureka-server-2
          uri: lb://eureka-client
          predicates:
            - Path=/test2/**

  application:
    name: getway-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server-1:8888/eureka/,http://eureka-server-3:9000/eureka/,http://eureka-server-2:8889/eureka/

