server:
  port: 8888
eureka:
  instance:
    hostname: eureka-server-1
#    instance-id: microcloud-provider-product
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔(默认是30秒)
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔(默认是90秒)
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位(默认是60秒)
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    register-with-eureka: true #是否将自己注册为服务  作为Eueka服务禁止将自己作为服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-3:9000/eureka/,http://eureka-server-2:8889/eureka/
spring:
  application:
    name: eureka-server-1